include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    invalid_annotation_target: ignore

linter:

  rules:
    # avoid_print: false
     prefer_single_quotes: truea
     always_use_package_imports: true

dart_code_metrics:
  rules-exclude:
    - ./**/*.g.dart
    - ./**/*.freezed.dart
  rules:
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-dynamic
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-redundant-async
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - list-all-equatable-fields
    - no-boolean-literal-compare
    - prefer-enums-by-name
    - prefer-first
    - prefer-last
    - prefer-immediate-return
    - prefer-match-file-name
    - prefer-moving-to-variable
    - avoid-cascade-after-if-null
    - binary-expression-operand-order
    - double-literal-format
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - prefer-correct-edge-insets-constructor
