name: halal_mobile_app
description: Mobile application with certified halal cafes and restaurants, and also with some information about food supplements.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  hive: ^2.2.3
  http: ^0.13.5
  google_nav_bar: ^5.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_crashlytics: ^3.1.1
  logger: ^1.3.0
  flutter_svg: ^2.0.5
  easy_search_bar: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
